Web1/Controllers/StatisticsEmployeesController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web1.Models;

namespace Web1.Controllers
{
   
    public class StatisticsEmployeesController : Controller
    { 
        private ServiceCenterEntities1 db = new ServiceCenterEntities1();

        public ViewResult Index()
        {
            return View();
        }

        
        // GET: Statistics
        public ActionResult Details(string currentFilter, string searchString ,int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            if ((String.IsNullOrEmpty(searchString) && page == 1))
            {
                TempData["msg"] = "1";
                return View();
            }
            else if (!String.IsNullOrEmpty(searchString) && searchString.Length > 1) {
                ModelState.AddModelError("", "Вы ввели не букву");
                TempData["msg"] = "1";
                return View();
            }
            else
            {
                TempData["msg"] = "";
            }
            string d1 = searchString;

            object[] parameters = {
                new SqlParameter("@date",SqlDbType.VarChar) {Value=d1}
            };
            db.Database.CommandTimeout = 360;
            IEnumerable<SP2_Result> query = db.Database.SqlQuery<SP2_Result>("SP2 @date", parameters).ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(query.ToPagedList(pageNumber, pageSize));
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
    
}

Web1/Views/StatisticsEmployees/Details.cshtml
@model PagedList.IPagedList<Web1.Models.SP2_Result>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Статистика по сотрудникам</h2>

@using (Html.BeginForm("Details", "StatisticsEmployees", FormMethod.Get))
{
    <div class="col-auto">
        <form asp-action="Index" method="get">
            <div class="form-actions no-color row">
                <div class="input-group mb-3">
                    <input type="text" id="SearchString" name="SearchString" class="form-control" placeholder="Буква" aria-label="Введите букву">
                    <input type="submit" value="Поиск" class="btn btn-outline-primary" />
                </div>
            </div>
        </form>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
}


@if (!TempData["msg"].Equals(""))
{
    <h1>Результатов не найдено </h1>
}

@if (TempData["msg"].Equals(""))
{
    <table class="table">
        <tr>
            <th>
                Имя сотрудника
            </th>
            <th>
                Минимальный возраст клиента
            </th>
            <th>
                Максимальный возраст клиента
            </th>
            <th>
                Количество записанных клиентов
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td> @Html.DisplayFor(modelItem => item.Name)</td>
                <td> @Html.DisplayFor(modelItem => item.MaxAgeClients)</td>
                <td> @Html.DisplayFor(modelItem => item.MinAgeClients)</td>
                <td> @Html.DisplayFor(modelItem => item.CountRecordClients)</td>
            </tr>
        }
    </table>

    <div class="row">
        <div class="col-auto">
            <form asp-action="Index" method="get">
                @Html.PagedListPager(Model, page => Url.Action("Details", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, currentFilter1 = ViewBag.CurrentFilter1 }))
            </form>
        </div>
        <div class="col-auto align-self-center">
            <span class="align-middle">Страница:  @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)  из  @Model.PageCount</span>
        </div>
    </div>
}

Web1/Views/StatisticsEmployees/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    
    <h2>Статистика по сотрудникам</h2>
    @using (Html.BeginForm("Details", "StatisticsEmployees", FormMethod.Get))
    {
        <div class="col-auto">
            <form asp-action="Index" method="get">
                <div class="form-actions no-color row">
                    <div class="input-group mb-3">
                        <input type="text" id="SearchString" name="SearchString" class="form-control" placeholder="Буква" aria-label="Введите букву">
                        <input type="submit" value="Поиск" class="btn btn-outline-primary" />
                    </div>
                </div>
            </form>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    }
</div>