Web1/Controllers/ClientsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web1.Models;

namespace Web1.Controllers
{
    public class ClientsController : Controller
    {
        private ServiceCenterEntities1 db = new ServiceCenterEntities1();

        // GET: Clients
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.SurameSortParm = String.IsNullOrEmpty(sortOrder) ? "Surname_desc" : "";
            ViewBag.NameSortParm = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.MiddleSortParm = sortOrder == "middle" ? "middle_desc" : "middle";
            ViewBag.PhoneSortParm = sortOrder == "phone" ? "phone_desc" : "phone";
            ViewBag.BirhdateSortParm = sortOrder == "birhdate" ? "birhdate_desc" : "birhdate";
            ViewBag.PostSortParm = sortOrder == "email" ? "email_desc" : "email";
            ViewBag.CommentSortParm = sortOrder == "comment" ? "comment_desc" : "comment";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var clients = from s in db.Clients
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(s => s.Name.Contains(searchString)
                || s.Surname.Contains(searchString)
                || s.Middle.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Surname_desc":
                    clients = clients.OrderByDescending(s => s.Surname);
                    break;
                case "name":
                    clients = clients.OrderBy(s => s.Name);
                    break;
                case "name_desc":
                    clients = clients.OrderByDescending(s => s.Name);
                    break;
                case "middle":
                    clients = clients.OrderBy(s => s.Middle);
                    break;
                case "middle_desc":
                    clients = clients.OrderByDescending(s => s.Middle);
                    break;
                case "phone":
                    clients = clients.OrderBy(s => s.Phone);
                    break;
                case "phone_desc":
                    clients = clients.OrderByDescending(s => s.Phone);
                    break;
                case "birhdate":
                    clients = clients.OrderBy(s => s.Birhdate);
                    break;
                case "birhdate_desc":
                    clients = clients.OrderByDescending(s => s.Birhdate);
                    break;
                default:  // Name ascending 
                    clients = clients.OrderBy(s => s.Surname);
                    break;
            }
            int pageSize =10;
            int pageNumber = (page ?? 1);
            return View(clients.ToPagedList(pageNumber, pageSize));
        }
        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clients clients = db.Clients.Find(id);
            if (clients == null)
            {
                return HttpNotFound();
            }
            return View(clients);
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Surname,Name,Middle,Birhdate,Email,Phone,Comment")] Clients clients)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var e = db.Clients.Where(s => s.Phone.Equals(((decimal)clients.Phone)));
                    if (e.Any())
                    {
                        ModelState.AddModelError("", "Клиент с таким номером телефона уже существует.");
                    }
                    else
                    {
                        db.Clients.Add(clients);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch
                {
                    ModelState.AddModelError("", "Клиент уже существует.");
                }
            }

            return View(clients);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clients clients = db.Clients.Find(id);
            if (clients == null)
            {
                return HttpNotFound();
            }
            return View(clients);
        }

        // POST: Clients/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Surname,Name,Middle,Birhdate,Email,Phone,Comment")] Clients clients)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(clients).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ModelState.AddModelError("", "Клиент уже существует.");
                }
            }
            return View(clients);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clients clients = db.Clients.Find(id);
            if (clients == null)
            {
                return HttpNotFound();
            }
            return View(clients);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Clients clients = db.Clients.Find(id);
            db.Clients.Remove(clients);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web1/Controllers/WorksController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web1.Models;

namespace Web1.Views
{
    public class WorksController : Controller
    {
        private ServiceCenterEntities1 db = new ServiceCenterEntities1();

        // GET: Works
        public ActionResult Index(string sortOrder, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "Date_desc" : "";
            ViewBag.TimeSortParm = sortOrder == "time" ? "time_desc" : "time";
            ViewBag.ClientsSortParm = sortOrder == "clients" ? "clients_desc" : "clients";
            ViewBag.IncomeSortParm = sortOrder == "income" ? "income_desc" : "income";
            ViewBag.EmployeeSortParm = sortOrder == "employee" ? "employee_desc" : "employee";
            ViewBag.ServicesSortParm = sortOrder == "services" ? "services_desc" : "services";

            var work = from s in db.Works
                         select s;
            switch (sortOrder)
            {
                case "Date_desc":
                    work = work.OrderByDescending(s => s.Date);
                    break;
                case "time":
                    work = work.OrderBy(s => s.Time);
                    break;
                case "time_desc":
                    work = work.OrderByDescending(s => s.Time);
                    break;
                case "income":
                    work = work.OrderBy(s => s.Income);
                    break;
                case "income_desc":
                    work = work.OrderByDescending(s => s.Income);
                    break;
                case "clients":
                    work = work.OrderBy(s => s.Id_Clients);
                    break;
                case "clients_desc":
                    work = work.OrderByDescending(s => s.Id_Clients);
                    break;
                case "employee":
                    work = work.OrderBy(s => s.Id_Employee);
                    break;
                case "employee_desc":
                    work = work.OrderByDescending(s => s.Id_Employee);
                    break;
                case "services":
                    work = work.OrderBy(s => s.Id_Services);
                    break;
                case "services_desc":
                    work = work.OrderByDescending(s => s.Id_Services);
                    break;
                default:  // Name ascending 
                    work = work.OrderBy(s => s.Date);
                    break;
            }
            int pageSize =  10;
            int pageNumber = (page ?? 1);
            return View(work.ToPagedList(pageNumber, pageSize));
        }

        
        // GET: Works/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Works work = db.Works.Find(id);
            if (work == null)
            {
                return HttpNotFound();
            }
            return View(work);
        }

        // GET: Works/Create
        public ActionResult Create()
        {
            ViewBag.Id_Employee = new SelectList(db.Employees, "Id", "FIO");
            ViewBag.Id_Services = new SelectList(db.Services, "Id", "Concat");
            return View();
        }

        // POST: Works/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Id_Services,Id_Employee,Date,Time,Income,Comment")] Works work)
        {
            var clients = from s in db.Clients select s;
            var Name = Request["Clients.Name"].ToString();
            var Surname = Request["Clients.Surname"].ToString();
            var Middle = Request["Clients.Middle"].ToString();
            var c = clients.Where(s => s.Name.Contains(Name)
                    & s.Surname.Contains(Surname)
                    & s.Middle.Contains(Middle)).FirstOrDefault();
            try
            {
                if (c != null)
                {
                    if (ModelState.IsValid)
                    {
                        work.Id_Clients = c.Id;
                        db.Works.Add(work);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                else {
                    ModelState.AddModelError("", "Клиента не существует");
                }
            }
            catch
            {
                ModelState.AddModelError("", "Работа уже существует.");
            }


            ViewBag.Id_Employee = new SelectList(db.Employees, "Id", "FIO", work.Id_Employee);
            ViewBag.Id_Services = new SelectList(db.Services, "Id", "Concat", work.Id_Services);
            return View(work);
        }

        // GET: Works/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Works work = db.Works.Find(id);
            if (work == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.Id_Employee = new SelectList(db.Employees, "Id", "FIO", work.Id_Employee);
            ViewBag.Id_Services = new SelectList(db.Services, "Id", "Concat", work.Id_Services);
            return View(work);
        }

        // POST: Works/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Id_Services,Id_Employee,Id_Clients,Date,Time,Income,Comment")] Works work)
        {
            var clients = from s in db.Clients select s;
            var Name = Request["Clients.Name"].ToString();
            var Surname = Request["Clients.Surname"].ToString();
            var Middle = Request["Clients.Middle"].ToString();
            var c = clients.Where(s => s.Name.Contains(Name)
                    & s.Surname.Contains(Surname)
                    & s.Middle.Contains(Middle)).FirstOrDefault();
            try
            {
                if (c != null)
                {
                    if (ModelState.IsValid)
                    {
                        work.Id_Clients = c.Id;
                        db.Entry(work).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Клиента не существует");
                }
            }
            catch
            {
                ModelState.AddModelError("", "Работа уже существует.");
            }

            ViewBag.Id_Employee = new SelectList(db.Employees, "Id", "FIO", work.Id_Employee);
            ViewBag.Id_Services = new SelectList(db.Services, "Id", "Concat", work.Id_Services);
            return View(work);
        }

        // GET: Works/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Works work = db.Works.Find(id);
            if (work == null)
            {
                return HttpNotFound();
            }
            return View(work);
        }

        // POST: Works/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Works work = db.Works.Find(id);
            db.Works.Remove(work);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
</head>

<body class="p-0">
    <script type="text/javascript">
        function shineLinks(id) {
            try {
                var el = document.getElementById(id).getElementsByTagName('a');
                var url = document.location.href;
                for (var i = 0; i < el.length; i++) {
                    var e = url.replace('' + el[i].origin + '', '');
                    if (e == '/') {
                        el[0].className += ' active';
                    } else if (e.search(el[i].id) != -1) {
                        el[i].className += ' active';
                    };
                };
            } catch (e) { }
        };
    </script>
    <div class="container-fluid ">
        <div class="row flex-nowrap ">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-light">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100" id="menu-act">
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Home",null)" id="/Home">
                                Главная
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index", "Services",null)" id="/Services">
                                Услуги
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index", "Employees",null)" id="/Employees">
                                Сотрудники
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index", "Clients",null)" id="/Clients">
                                Клиенты
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index", "Works",null)" id="/Works">
                                Работы
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index", "Records",null)" id="/Records">
                                Записи
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index", "StatisticsServices",null)" id="/StatisticsServices">
                                Статистика по услугам
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index", "StatisticsEmployees",null)" id="/StatisticsEmployees">
                                Статистика по сотрудникам
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col py-3">
                @RenderBody()
                <script type="text/javascript">shineLinks('menu-act');</script>
            </div>
        </div>
    </div>

   
    
    @Scripts.Render("~/bundles/jquery-3.6.0.js")
    @Scripts.Render("~/bundles/bootstrap.bundle.js")
    @RenderSection("scripts", required: false)
    @RenderSection("Serv", required: false)
</body>
</html >